In [13]:
from matplotlib import pyplot as plt
import numpy as np
import random
import chess
import chess.svg

In [14]:
# Population size
#size_ppl = int(input("Population size:"))
size_ppl = int(100)

In [15]:
def permutation2array(permutation):
    array = np.zeros(64)
    array = array.reshape((8,8))
    for i in range(8):
        indx = permutation[i]
        array[indx][i] = 1
    return array

In [16]:
def fitnessFunction(solution):
    row_queens = 0
    col_queens = 0
    dig_queens = 0
    for row in range(solution.shape[0]):
        if (np.sum(solution[row,:]) > 1):
            row_queens += np.sum(solution[row,:]) - 1
    for col in range(solution.shape[1]):
        if (np.sum(solution[:,col]) > 1):
            col_queens += np.sum(solution[:,col]) - 1
    for i in range(-7,7):
        if (np.trace(solution, i) > 1):
            dig_queens += np.trace(solution, i) - 1
        if (np.trace(np.rot90(solution), -i) > 1):
            dig_queens += np.trace(np.rot90(solution), -i) - 1        
    return int(row_queens+col_queens+dig_queens)

In [17]:
def generatePopulation(size):
    population = []
    apptitudes = []
    for index in range (0,size):
        queens = random.sample(range(0, 8), 8)
        # 2. Fitness or aptitude  function with attacks
        apptitude = fitnessFunction(permutation2array(queens))
        apptitudes.append((index,apptitude))
        # 3. Solution population of boards
        population.append(queens)
        #print("{} <--- atacks {} \n".format(solution.astype(int), apptitude))
    return population, apptitudes

In [18]:
def parentSelection(population, fitness):
    parents = random.sample(range(0, len(fitness)), 5)
    temp = []
    for i in parents:
        temp.append(fitness[i])
    temp.sort(key=lambda a: a[1])
    index_1 = temp[0]
    index_2 = temp[1]
    
    parent_1 = population[index_1[0]]
    parent_2 = population[index_2[0]]
    return fitness, parent_1, parent_2 

In [19]:
def crossBoard(solution1, solution2):    
    cross_pt = random.randint(0, 9)
    first_half1  = solution1[:cross_pt]
    second_half1 = solution1[cross_pt:]
    first_half2  = solution2[:cross_pt]
    second_half2 = solution2[cross_pt:]
    sol_1 = np.concatenate((first_half1,second_half2))
    sol_2 = np.concatenate((first_half2,second_half1))
    return sol_1, sol_2

In [20]:
def repairBoard(solution):
    solution.sort()
    toadd = []
    for i in range(8):
        if ((i in solution) == False):
            toadd.append(i)
    a,b = np.unique(solution, return_counts=True)
    todel = []
    for i in range(len(b)):
        if (b[i] > 1):
            todel.append(a[i])
    #print(todel)
    for j in todel:
        #print(j)
        #print(solution)
        solution[j] = 10
    solution = np.delete(solution, np.where(solution == 10))
    #print(solution)
    for i in toadd:
        solution = np.append(solution,i)
    return solution

In [21]:
best_fitness = []
best_average = []
# 1. Representation, 2. Fitness and 3. Population
population, apptitudes = generatePopulation(size_ppl)
# 4. Parent selection
apptitudes, parent_1, parent_2 = parentSelection(population, apptitudes)

In [22]:
son_1, son_2 = crossBoard(parent_1, parent_2)
print(son_1)
print(son_2)

[0 3 2 0 6 3 7 5]
[4 1 1 6 2 5 7 4]


In [23]:
if (len(np.unique(son_1))) != 8:
    son_1 = repairBoard(son_1)
print(son_1)


[0 2 3 5 6 7 1 4]


In [24]:
if (len(np.unique(son_2))) != 8:
    son_2 = repairBoard(son_2)
print(son_2)

[1 2 4 5 6 7 0 3]
