In [1]:
from matplotlib import pyplot as plt
import numpy as np
import random
import chess
import chess.svg

In [2]:
# Population size
#size_ppl = int(input("Population size:"))
size_ppl = int(100)

In [3]:
def permutation2array(permutation):
    array = np.zeros(64)
    array = array.reshape((8,8))
    for i in range(8):
        indx = permutation[i]
        array[indx][i] = 1
    return array

In [4]:
def fitnessFunction(solution):
    row_queens = 0
    col_queens = 0
    dig_queens = 0
    for row in range(solution.shape[0]):
        if (np.sum(solution[row,:]) > 1):
            row_queens += np.sum(solution[row,:]) - 1
    for col in range(solution.shape[1]):
        if (np.sum(solution[:,col]) > 1):
            col_queens += np.sum(solution[:,col]) - 1
    for i in range(-7,7):
        if (np.trace(solution, i) > 1):
            dig_queens += np.trace(solution, i) - 1
        if (np.trace(np.rot90(solution), -i) > 1):
            dig_queens += np.trace(np.rot90(solution), -i) - 1        
    return int(row_queens+col_queens+dig_queens)

In [5]:
def generatePopulation(size):
    population = []
    apptitudes = []
    for index in range (0,size):
        queens = random.sample(range(0, 8), 8)
        # 2. Fitness or aptitude  function with attacks
        apptitude = fitnessFunction(permutation2array(queens))
        apptitudes.append((index,apptitude))
        # 3. Solution population of boards
        population.append(queens)
        #print("{} <--- atacks {} \n".format(solution.astype(int), apptitude))
    return population, apptitudes

In [6]:
def parentSelection(population, fitness):
    parents = random.sample(range(0, len(fitness)), 5)
    temp = []
    for i in parents:
        temp.append(fitness[i])
    temp.sort(key=lambda a: a[1])
    index_1 = temp[0]
    index_2 = temp[1]
    
    parent_1 = population[index_1[0]]
    parent_2 = population[index_2[0]]
    return fitness, parent_1, parent_2 

In [7]:
def crossBoard(solution1, solution2):    
    cross_pt = random.randint(0, 9)
    first_half1  = solution1[:cross_pt]
    second_half1 = solution1[cross_pt:]
    first_half2  = solution2[:cross_pt]
    second_half2 = solution2[cross_pt:]
    sol_1 = np.concatenate((first_half1,second_half2))
    sol_2 = np.concatenate((first_half2,second_half1))
    return sol_1, sol_2

In [8]:
best_fitness = []
best_average = []
# 1. Representation, 2. Fitness and 3. Population
population, apptitudes = generatePopulation(size_ppl)
# 4. Parent selection
apptitudes, parent_1, parent_2 = parentSelection(population, apptitudes)

In [9]:
son_1, son_2 = crossBoard(parent_1, parent_2)
print(son_1)
print(son_2)

[6 0 3 0 6 7 5 1]
[4 3 2 1 4 5 7 2]


In [10]:
son_1.sort()
for i in range(8):
    if ((i in son_1) == False):
        print("falta un", i)

falta un 2
falta un 4


In [11]:
a,b = np.unique(son_1, return_counts=True)
print(a)
print(b)
for i in range(len(b)):
    if (b[i] > 1):
        print("sobra un", a[i])

[0 1 3 5 6 7]
[2 1 1 1 2 1]
sobra un 0
sobra un 6
